### ISSUE TITLE
Problem 4 (biweekly contest 100)

### ISSUE THREAD

**Issue by davidosx** [RuslansAleksejevs/algorithms-and-structures#1]
решение задачи 4 без костыля:
```py
class Solution:
    def repairCars(self, ranks: List[int], cars: int) -> int:
        left, right = 1, min(ranks)*cars*cars
        total = 0
        while left <= right:
            mid = (left+right)//2
            total = 0
            for rank in ranks: total += isqrt(mid//rank)
            if total >= cars: right = mid - 1
            else: left = mid + 1
        
        return left
```

**Comment by RuslansAleksejevs** [comment]
Действительно работает, да и код поизящнее. Я вдохновился и заменил в своем бинарном поиске строгое неравенство на нестрогое и return res на return res+1, и все тоже заработало без костыля. Спасибо.

Правда, меня смущает, что твой код почему-то в 2 раза медленнее моего (хоть и короче раза в 2-3). У нас ведь все одинаково происходит, только у меня еще дополнительно $n\log(n)$ уходит на сортировку в начале, а ты абсолютно разумно заменяешь это на линейный поиск минимума. Казалось бы, это твой код должен быть почти в 2 раза быстрее.
